# Change these first
owner: Wandashabba
repo: vitrafruits-status 

sites:
  - name: VitraFruits
    url: https://www.vitrafruits.co.za

status-website:
  baseUrl: /vitrafruits-status
  logoUrl: https://www.vitrafruits.co.za/images/logo.jpg
  name: VitraFruits Status
  introTitle: "**VitraFruits** System Status."
  introMessage: "Real-time monitoring of the VitraFruits website. This page is updated automatically every 5 minutes."
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# This enables the email alerts
notifications:
  - type: mail
