# Change these first
owner: Wandashabba
repo: vitrafruits-status # Make sure this matches the exact name of the GitHub repository you created

sites:
  - name: VitraFruits
    url: https://vitrafruit.com

status-website:
  # We use baseUrl instead of cname since you don't have a custom status domain yet
  baseUrl: /vitrafruits-status
  logoUrl: https://vitrafruit.com/images/logo.jpg
  name: VitraFruits Status
  introTitle: "**VitraFruits** System Status."
  introMessage: "Real-time monitoring of the VitraFruits website. This page is updated automatically every 5 minutes."
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# This enables the email alerts
notifications:
  - type: mail
